### PR TITLE
Move some test files created during testing into this repo

### PR DESCRIPTION
**Pull request by ahill187**
### `my_testfile.hdf5`
In `ivadomed/testing/unit_tests/test_HeMIS`, one of the tests (`test_HeMIS`) creates a file called `mytestfile.hdf5`, while the second test (`test_hdf5_bids`) uses that file to test `HDF5ToBIDS`. However, this means that if the first test fails, the second test will automatically fail. Ideally, we should keep tests separate, so they don't depend on each other.

### `model_unet_test.pt`
In `ivadmoed/testing/unit_tests/ivado_test.py`, a file called `model_unet_test.pt` is created each time the test suite is run. This file is used by `test_transfer_learning`. I think it makes more sense to just download this file instead of recreating it each time.

I am creating another pull request in `ivadomed` to have the unit tests clean up after they run (https://github.com/ivadomed/ivadomed/pull/636); we should wait to create a new release from this PR until that one is finished because I think this one will cause a `FileExists` error as-is.

### CODE REVIEW

**Comment by andreanne-lemay** [comment]
`model_unet_test.pt` is 18.5Mb which is >> than the whole repo. I'll generate a smaller model (with less filters, less depth) to use during the test.

**Comment by ahill187** [comment]
> `model_unet_test.pt` is 18.5Mb which is >> than the whole repo. I'll generate a smaller model (with less filters, less depth) to use during the test.

Oh good point! Yah I didn't realize it was so big until I went to push and it took a long time...

**Comment by andreanne-lemay** [comment]
It's now 60kb: 48a516a

**Review by andreanne-lemay — APPROVED** [review]
:rocket:

**Comment by ahill187** [comment]
> It's now 60kb: [48a516a](https://github.com/ivadomed/data-testing/commit/48a516a49e7036c71529df2cbc5df87a3fc9d420)

Thank you!!!

**Comment by jcohenadad** [comment]
make sure to squash as always 😊

**Pull request merged**
